(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(org-babel-load-file (expand-file-name "~/.emacs.d/el/myinit.org"))
(require 'init-package)
(require 'init-ui)
(require 'init-org)
(require 'init-better-defaults)
(require 'init-keybindings)
;;(require 'org-dev)
(setq custom-file (expand-file-name "el/custom.el" user-emacs-directory))

(load-file custom-file)
(message "init success!")
